- name: play1
  hosts: all
  remote_user: ec2-user
  become: true
  tasks:
   - name: Create a login user
     user:
      name: test-pc
      password: $1$SomeSalt$UqddPX3r4kH3UL5jq5/ZI.
      groups: wheel   
      state: present

