- name: play1
  hosts: all
  remote_user: ec2-user
  become: true
  tasks:
   - name: Create a login user
     user:
      name: test-pc
      password: "$6$pCNgiQprrT/EmeE5$G7wa6wYm1FyuBHeVsuyH9IXGju07csuFwtrynslvSz6O.wFv4Ub8ADPqlBseewQQZQfp.9LCkWyodvJQjH.fe0"
      groups: wheel   
      state: present

